### ISSUE TITLE
Deprecation of firebase_admob Plugin

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/ads#38]
Migrate dependency because The firebase_admob plugin will be deprecated in April 2021 in favor of Google Mobile Ads SDK for Flutter.

**Comment by Andrious** [comment]
Yes, I'm working on that this weekend.

**Comment by deadsoul44** [comment]
Any update? Thank you very much.

**Comment by Andrious** [comment]
I will be working on it for the next three days.

**Comment by Andrious** [comment]
Beta version 3.0.0. is now available.  New versions will be released in subsequent days.

**Comment by deadsoul44** [comment]
I get this error when trying to show interstitial ad.

```
E/flutter ( 8772): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8772): #0      FullScreenAd._createAd (package:ads/admob.dart:255:23)
E/flutter ( 8772): #1      MobileAds.loadAd (package:ads/admob.dart:559:9)
E/flutter ( 8772): <asynchronous suspension>
E/flutter ( 8772): #2      Ads.showFullScreenAd (package:ads/ads.dart:640:14)
E/flutter ( 8772): <asynchronous suspension>
```
Any idea how to solve it?

**Comment by deadsoul44** [comment]
I have to provide `unitId` to `showFullScreenAd` method in order to surpass the error above. But, now, ads fail to load.
```
Ad failed to load : 3
```
Any idea what could be the problem? Thank you.

**Comment by Marek00Malik** [comment]
I have the same problem, when trying to run rewardAds, did you manage to fix your problem?

**Comment by Andrious** [comment]
I will look into it this evening.

**Comment by Andrious** [comment]
ads 3.0.1. has been released.
