### ISSUE TITLE
Support google_mobile_ads ^0.13.0

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/ads#40]
Support google_mobile_ads ^0.13.0

**Comment by Andrious** [comment]
Turns out version 0.13.0 was a Major change to the plugin, google_mobile_ads:  [Major version update - tracking all changes](https://github.com/googleads/googleads-mobile-flutter/commit/a2c7afe02bcb9f5f03cbf81d271dd4c5b24600be#diff-060189bacfe2753fbe0e53992ec637fad2f8b7d01bbfec29258ceca6fd24990d)

This will take time to migrate.
If you need to use their latest features now, I would suggest you review how this latest plugin is implemented in their [example app](https://github.com/googleads/googleads-mobile-flutter/tree/a2c7afe02bcb9f5f03cbf81d271dd4c5b24600be/packages/google_mobile_ads/example).

**Comment by deadsoul44** [comment]
I upgraded to Flutter 2.5.0 and now getting exception at the start. I wonder if it is related to this.

**Comment by deadsoul44** [comment]
```
E/AndroidRuntime(16555): FATAL EXCEPTION: main
E/AndroidRuntime(16555): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
E/AndroidRuntime(16555): 	at io.flutter.plugins.googlemobileads.FlutterInterstitialAd.load(FlutterInterstitialAd.java:70)
E/AndroidRuntime(16555): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:302)
E/AndroidRuntime(16555): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(16555): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(16555): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(16555): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
E/AndroidRuntime(16555): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(16555): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16555): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(16555): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/AndroidRuntime(16555): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16555): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
E/AndroidRuntime(16555): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
E/AndroidRuntime(16555): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.InterstitialAd" on path: DexPathList[[zip file "/data/app/iomutlutech.github.deadsoul44.bettingai-2/base.apk"],nativeLibraryDirectories=[/data/app/iomutlutech.github.deadsoul44.bettingai-2/lib/arm, /data/app/iomutlutech.github.deadsoul44.bettingai-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(16555): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(16555): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime(16555): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(16555): 	... 13 more
Lost connection to device.

```

Now, I get fatal exception when trying to show an ad.

**Comment by deadsoul44** [comment]
```
E/AndroidRuntime(16555): FATAL EXCEPTION: main
E/AndroidRuntime(16555): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
E/AndroidRuntime(16555): 	at io.flutter.plugins.googlemobileads.FlutterInterstitialAd.load(FlutterInterstitialAd.java:70)
E/AndroidRuntime(16555): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:302)
E/AndroidRuntime(16555): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(16555): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(16555): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(16555): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
E/AndroidRuntime(16555): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(16555): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16555): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(16555): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/AndroidRuntime(16555): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16555): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
E/AndroidRuntime(16555): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
E/AndroidRuntime(16555): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.InterstitialAd" on path: DexPathList[[zip file "/data/app/-2/base.apk"],nativeLibraryDirectories=[/data/app2/lib/arm, /data/app2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(16555): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(16555): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime(16555): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(16555): 	... 13 more
Lost connection to device.

```

Now, I get fatal exception when trying to show an ad.

**Comment by Andrious** [comment]
Mutlu,

It's been wonderful. 

You've used my Ad package right from the beginning when it was first published.

However, I'm no longer supporting the package and 'unlisted' it from [Pub.dev](https://pub.dev/packages/ads).

The plugin it uses has advanced so much that the package is no longer useful.

Again, I would suggest you review how the plugin is now implemented in their [example app](https://github.com/googleads/googleads-mobile-flutter/tree/a2c7afe02bcb9f5f03cbf81d271dd4c5b24600be/packages/google_mobile_ads/example) and use that approach instead.

I know I will.

Best regards,

Greg

**Comment by deadsoul44** [comment]
Thank you very much Greg. It was a great package :(
